gridsome/gridsome

packages/source-contentful/index.js
=> fix(souce-contentful): define all types before creating nodes

packages/source-datocms/CHANGELOG.md, packages/source-datocms/README.md, packages/source-datocms/index.js, packages/source-datocms/package.json
Alright @hjvedvik, this works with gridsome version on master! The only thing that's not working is refs with multiple nodes, but I think that's related to this https://github.com/gridsome/gridsome/blob/master/gridsome/lib/graphql/schema/nodes/createType.js#L127-L130
Let me know if everything's fine with this PR!
=> @gridsome/source-datocms plugin

packages/remark-prismjs/index.js
=> fix: load all languages

packages/source-faker/index.js
allow to modify the route for faker plugin
=> extend the configuration for faker plugin

packages/source-contentful/index.js
This PR should fix issue #94. Add ContentfulAsset ContentType.
=> feat(contentful): Add ContentfulAsset

packages/transformer-yaml/README.md, packages/transformer-yaml/index.js, packages/transformer-yaml/package.json
This PR add `@gridsome/transformer-yaml` plugin to gridsome.
This should close #131.
=> feat(transformer-yaml): add transformer

gridsome/lib/app/loadConfig.js
=> Fix for "ReferenceError: icon not defined"

gridsome/app/head.js
I wanted to override default viewport information, but I could not.
=> Added key to viewport

gridsome/app/page-query/fetch.js, gridsome/app/page-query/sock.js, gridsome/lib/app/App.js, gridsome/lib/app/loadConfig.js, gridsome/lib/develop.js, gridsome/lib/webpack/createBaseConfig.js, gridsome/package.json, yarn.lock
fix #88 and #58 
Code and specification referenced Nuxt.js ([doc](https://nuxtjs.org/api/configuration-env/)).
- Add `env` config to `gridsome.config.js`
- Make it possible to access these configs in Vue
- Attach environment variables start with `GRIDSOME_ENV` to `process.env`
- Add `process.env.NODE_ENV` and `process.isProduction` to base env config.
---
If need document, I will try to create it after review.
=> feat(webpack): make it possible to add enviroment variables

packages/cli/lib/commands/create.js
It would be awesome if we could create a new project in the current directory:
```
gridsome create .
```
=>  Allow user to create project in current directory

gridsome/app/components/Image.js
=> fix(g-image): add missing classes

packages/remark-prismjs/README.md
I struggled here about that : https://github.com/gridsome/gridsome/issues/242 
---
Closes #242.
=> explain than a css theme is required

gridsome/lib/app/loadConfig.js
fixes #265 
---
[Lodash Documentation](https://lodash.com/docs/#defaultsDeep)
=> fix(app): update default configuration

packages/transformer-csv/README.md, packages/transformer-csv/__tests__/index.spec.js, packages/transformer-csv/index.js, packages/transformer-csv/package.json, yarn.lock
Adds `@gridsome/transformer-csv` plugin to parse `csv` sources. Closes #282.
=> feat(transformer-csv): add csv transformer

README.md
=> Fixed and Updated README.md

gridsome/package.json, yarn.lock
=> Update sharp for supporting Node 12.x

packages/source-drupal/README.md
@Al-Rozhkov please review and make suggestions! Thanks.
You'll see in the update README I link to a commented out section in the [Starter Package `gridsome.config.js`](https://github.com/matt-e-king/gridsome-starter-drupal/blob/master/gridsome.config.js). Let me know if you think this is enough.
=> Table of Contents; new Contenta CMS section

packages/source-contentful/index.js
=> fix(contentful): fixed wrong variable name that caused an infinite loop

packages/source-filesystem/README.md
Looks like this got missed being documented, found via discord.
=> chore(filesystem): update docs for index option

gridsome/lib/explore.js
@hjvedvik I suppose that `serve` is correct mode in `explore`
=> fix: GRIDSOME_MODE in explore

.eslintignore, gridsome/.eslintrc.js, gridsome/lib/__tests__/__fixtures__/project-basic/src/main.js, gridsome/lib/__tests__/__fixtures__/project-blog/src/main.js, gridsome/lib/__tests__/__fixtures__/project-path-prefix/src/main.js, gridsome/lib/app/ComponentParser.js, gridsome/lib/app/__tests__/ImageProcessQueue.spec.js, gridsome/lib/app/codegen/constants.js, gridsome/lib/app/loadConfig.js, gridsome/lib/app/queue/FileProcessQueue.js, gridsome/lib/app/queue/ImageProcessQueue.js, gridsome/lib/build.js, gridsome/lib/graphql/createFilterTypes.js, gridsome/lib/graphql/nodes/createConnection.js, gridsome/lib/plugins/core/index.js, gridsome/lib/server/middlewares/graphql.js, gridsome/lib/utils/constants.js, gridsome/lib/webpack/createBaseConfig.js, gridsome/lib/webpack/modules/assets.js, package.json, yarn.lock
@hjvedvik 
- Add lint for tests and fixtures
- Add eslint-plugin-import
- Fix some link errors in tests and fixtures
=> chore: lint tests & projects and add eslint-plugin-import

packages/cli/bin/gridsome.js, packages/cli/package.json, yarn.lock
Fixes #476 
Suggests matching commands if the user mistypes.
=> feat(cli): suggest matching commands

gridsome/lib/app/__tests__/ImageProcessQueue.spec.js, gridsome/lib/app/queue/ImageProcessQueue.js, gridsome/lib/workers/image-processor.js
=> fix g-image sizing for fit inside and fit outside

packages/source-filesystem/index.js
Eg. `*.vue` files get mime type `application/x-vue`
=> Add fallback mime type if false

packages/vue-remark/README.md
=> chore(docs): vue-remark

packages/cli/lib/commands/create.js
Use `includes()` to check for existence.
=> chore: minor stylistic code refactor

package.json, packages/cli/bin/gridsome.js, packages/cli/lib/commands/info.js, packages/cli/package.json, yarn.lock
=> feat: new info command

packages/cli/lib/commands/create.js
Maybe this position is easy to understand.
=> refactor(cli): change how to management command names

gridsome/lib/app/__tests__/FileProcessQueue.spec.js, gridsome/lib/app/__tests__/ImageProcessQueue.spec.js, gridsome/lib/app/__tests__/createRenderQueue.spec.js, gridsome/lib/app/build/createRenderQueue.js, gridsome/lib/app/codegen/index.js, gridsome/lib/app/loadConfig.js, gridsome/lib/app/queue/FileProcessQueue.js, gridsome/lib/app/queue/ImageProcessQueue.js, gridsome/lib/build.js, gridsome/lib/graphql/__tests__/metadata.spec.js, gridsome/lib/graphql/__tests__/nodes.spec.js, gridsome/lib/plugins/RedirectsPlugin.js, gridsome/lib/plugins/core/index.js, gridsome/lib/serve.js, gridsome/lib/server/Server.js, gridsome/lib/webpack/createBaseConfig.js, gridsome/lib/webpack/createClientConfig.js, gridsome/lib/webpack/createServerConfig.js, gridsome/lib/webpack/utils.js, gridsome/lib/workers/__tests__/image-processor.spec.js, packages/plugin-critical/index.js, packages/plugin-sitemap/index.js
Proposing to change the `outDir` config setting to be `outputDir`. To be in line with vue-cli convention: https://cli.vuejs.org/config/#outputdir
=> refactor: outDir to outputDir

gridsome/app/components/Link.js, gridsome/app/utils/helpers.js, gridsome/lib/utils/index.js, gridsome/lib/webpack/modules/assets.js
Have `mailto` and `tel` links also go to the attrs.href of the router-link.
=> fix: mailto and tel links in g-link

packages/source-ghost/index.js
Fix the url in the "Loading data from undefined" console message while building.
=> Update url to baseUrl

gridsome/lib/pages/__tests__/pages.spec.js, gridsome/lib/pages/pages.js
Added these missing methods - hope they are implemented correctly...
Can also add documentation for them if needed?
=> feat(Pages API) Add missing find* API methods

gridsome/app/entry.client.js, gridsome/lib/app/codegen/config.js, gridsome/lib/app/loadConfig.js
=> Add a config flag to disable the event listener on normal anchor links

gridsome/lib/__tests__/project-basic.build.e2e.js, gridsome/package.json, yarn.lock
=> bump up @vue/babel-preset-app to ^4.2.2

packages/vue-remark/README.md, packages/vue-remark/index.js
=> Add possibility to ignore files when using vue-remark

gridsome/lib/app/Schema.js, gridsome/lib/app/actions.js
=> feat: pass operationName argument for graphql

packages/cli/__tests__/gridsome.spec.js
=> chore: test case for command suggestion logic

packages/cli/package.json, yarn.lock
Should fix https://app.snyk.io/vuln/SNYK-JS-DOTPROP-543489.
=> cli/update-notifier: 4.1.0

packages/transformer-remark/index.js, packages/transformer-remark/lib/timeToRead.js
This PR implements reading time estimations with respect to CJK characters. After looking at various implementations (including [gatsby-transformer-remark](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/utils/time-to-read.js), [word-count](https://github.com/yuehu/word-count/blob/master/index.js)), I found that the `word-count` library seems to be the most accurate one. The library itself is quite simple, so I implemented the feature directly inside Gridsome `@gridsome/transformer-remark`.
I tested the implementation with the following article (click to expand):
<details>
<summary><b>CJK reading time implementation test:</b></summary>
```
Vue (pronounced /vjuː/, like view) is a progressive framework for building user interfaces. Unlike other …
```
=> feat(remark): timeToRead with CJK support

packages/cli/lib/commands/create.js
=> feat(cli): create command warns if the target path exists and is non-empty

gridsome/app/entry.client.js
=> fix(app): resolve anchor encoding issue (#1281)

packages/cli/lib/commands/create.js
=> fix: prefer npm if the starter template has package-lock.json

gridsome/app/components/Image.js
=> fix(<g-image>): proper immediate typing and behaviour

gridsome/app/components/Link.js
=> fix(<g-link>): make sure that other domProps are properly passed to <router-link>

packages/source-datocms/index.js, packages/source-datocms/package.json, yarn.lock
To use new version of DatoCMS JS client.
I've meanwhile fixed a bug with model names with characters different from letters and numbers.
=> Upgrade source-datocms

gridsome/package.json, yarn.lock
Updated @sindresorhus/slugify to include new bug fixes.
=> chore(deps): bump @sindresorhus/slugify from 0.8.0 to 1.1.0

gridsome/lib/develop.js
=> fix: yarn PnP in develop

.editorconfig
EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.
Most editors support it but some need a plugin
https://editorconfig.org/
https://editorconfig.org/#download
=> feat: add EditorConfig config file

gridsome/lib/graphql/types/image.js, gridsome/lib/graphql/types/index.js
Adds an enum with the valid values for `position`.
Fixes #1283
=> feat(gridsome): Support the `position` option on images in GraphQL
