gridsome/gridsome

gridsome/__tests__/PluginStore.spec.js
gridsome/__tests__/__fixtures__/JSONTransformer.js
gridsome/__tests__/schema.spec.js
gridsome/lib/app/App.js
gridsome/lib/app/BaseStore.js
gridsome/lib/app/ContentTypeCollection.js
gridsome/lib/app/PluginAPI.js
gridsome/lib/app/PluginStore.js
gridsome/lib/utils/index.js
gridsome/package.json
package.json
yarn.lock

This PR resolves all relative file paths in node fields. It also makes it possible to resolve absolute paths with a `resolveAbsolutePaths` option. That will make Gridsome able to process image paths from Netlify CMS etc.
When a field contains `/images/image.png`, Gridsome normally assumes the image is located in `/static/images/*` and leave the field as is, since they will be copied during deployment. But Gridsome will convert the field into an absolute file path resolved from the root folder if `resolveAbsolutePaths` is `true`. Your images should be located at `{root}/images/*`. The option can also take an absolute path to a folder containing the referenced files.
It also works for urls. Absolute pathnames like `/image.jpg` converts into absolute urls when `resolveAbsolutePaths` is …

Resolve file paths in node fields

---

gridsome/__tests__/PluginStore.spec.js
gridsome/__tests__/schema.spec.js
gridsome/lib/app/ContentTypeCollection.js
gridsome/lib/app/PluginStore.js
gridsome/lib/graphql/schema/infer-types.js
gridsome/lib/graphql/schema/interfaces.js
gridsome/lib/graphql/schema/nodes/createQuery.js
gridsome/lib/graphql/schema/nodes/createType.js
gridsome/lib/graphql/schema/pages/index.js
gridsome/lib/graphql/schema/resolvers.js
gridsome/lib/graphql/schema/types.js
gridsome/lib/graphql/schema/types/date.js

Flattening node types in schema by moving all fields and refs properties to the node instead. `fields.*` and `refs.*` will still be available, but marked as deprecated. Also inserts `id`, deprecating `_id` and removing `internals` from schema. These node fields cannot be overridden by custom fields: `id`, `title`, `slug`, `path`, `date`, `content` and `excerpt`.

Cleanup GraphQL schema

---

packages/source-wordpress/index.js

See [this issue](https://github.com/gridsome/gridsome/issues/47) for more details. Adding a guard for line 97's collection seems to fix the problem.

Fix "Cannot read property 'addReference' of undefined" error

---

gridsome/lib/graphql/schema/nodes/createType.js

@hjvedvik According to the documentation for `collection.addSchemaField`, the callback function should receive an object with a property of `graphql`. 
This wasn't working for me - do these modifications to the `createType.js` fix that?

collection.addSchemaField fix

---

packages/source-contentful/README.md
packages/source-contentful/index.js

Adds a check for `sys` on fields that return an object before passing them to `this.createReferenceField`. Because the Location and JSON content types return objects without `sys` we can simply return the `value`
- Fixes #129
- adds examples and docs to README

Fixes errors with JSON and Location content types

---

gridsome/lib/app/loadConfig.js
gridsome/lib/webpack/createBaseConfig.js

I need the possibility to configure the SCSS loader options in all of my projects. I guess it is possible via chain-webpack but I couldn't get it to work. I think exposing the loader options directly makes this a lot easier.

feat: make style loader options configurable

---

gridsome/app/components/Pager.js

Added additional props to Pager component to allow css class overrides on generate links and nav element
PS: This is my first contribution to OSS, so let me know if there's anything I should do differently next time :D

feat(pager-class-props): Support for additional css class overrides

---

gridsome/lib/app/loadConfig.js

This small PR basically allows someone to add an `index.html` to their `/src` directory and override the default template. It's probably not going to happen very often, but it's the easiest way to allow people to add CDN/external scripts to the footer of their site.

Allow index.html template to be overridden

---

gridsome/lib/webpack/createBaseConfig.js

This adds `webp` suffix to the webpack rule for images.

Adds support for (existing) webp images

---

gridsome/app/entry.client.js

I often navigate documentation sites by right clicking to open a link in a new tab, but I found that this was unexpectedly causing the browser to navigate. This makes it very difficult to browse.
This pull request simply ignores any clicks that don't use the left mouse button.
I hope this is in the right place. It was the only code i could see that looked like it would be causing the behaviour I was seeing.

Only intercept left clicks on links

---

gridsome/lib/utils/sysinfo.js

physical-cpu-count depends on lscpu on linux, which is not standard in all distros (ie. alpine) and on error returns 0, which breaks the build process with a message "Expected `concurrency` to be a number from 1 and up, got `0` (number)".
This fix returns 1 if the number of cpus is 0 (may as well return cpus.length, but that would defeat the original intention)

number of cpus defaults to 1

---

gridsome/lib/server/middlewares/graphql.js

#134 
When using Docker, I set host option. Unfortunately Gridsome does not work. This problem is caused by that express-graphql accepts only `GET` or `POST` http methods. This PR resolves by accepting `OPTIONS` method in Gridsome's graphql middleware.
command: `gridsome develop -h 0.0.0.0`
url: `localhost:8080`
result:
command: `gridsome develop -h 0.0.0.0`
url: `localhost:8080`
result:

allow OPTIONS method request to /___graphql

---

gridsome/lib/app/ContentTypeCollection.js
gridsome/lib/app/PluginStore.js
gridsome/lib/app/__tests__/PluginStore.spec.js

This fixes #277. Routes now support repeated path segments. Repeated keys with an array value are handled as expected:
```js
const examples = store.addContentType({
typeName: 'Example',
route: '/path/:segments+'
})
const node = examples.addNode({
fields: {
segments: ['a', 'b', 'c']
}
})
console.log(node.path)
// Output: '/path/a/b/c'
```
The elements of the array are slugified unless you use the `_raw` suffix. `['foo bar', 'HELLO']` would result in `'/foo-bar/hello'` with `/:segments+` and `'/foo%20bar/HELLO'` with `/:segments_raw+`.
Note that node references also work:
```js
const node = examples.addNode({
fields: {
segments: [
{ typeName: 'Test', id: 1 },
{ typeName: 'Test', id: 2 }
]
}
})
console.log(node.path)
// Output: '/path/1/2'
```
I tried to keep the internal changes to a …

Support repeated path segments in dynamic routes

---

gridsome/lib/app/ContentTypeCollection.js
gridsome/lib/app/PluginStore.js
gridsome/lib/app/__tests__/PluginStore.spec.js

This fixes #294. Deeply nested field references will now work properly if the field name starts with `raw`. The field name and the suffix are now separated with a regular expression instead of removing every occurrence of `_raw` in the key with [`key.name.replace('_raw', '')`](https://github.com/vberlier/gridsome/blob/2259f85de11f0b0139d2c0cfac87c6be0217ae35/gridsome/lib/app/PluginStore.js#L97).
```js
const contentType = store.addContentType({
typeName: 'TestPost',
route: '/:foo__rawValue'
})
const node = contentType.addNode({
fields: {
foo: {
rawValue: 'BAR'
}
}
})
console.log(node.path) // Output: '/bar'
```
Every element of the `routeKeys` array now has an additional `suffix` property that holds either the value of the suffix or `null` if the key doesn't have any suffix.

Fix field name and suffix separation

---

packages/source-drupal/README.md

This would fix a small piece of the [Drupal plugin docs](https://github.com/gridsome/gridsome/tree/master/packages/source-drupal#example-page-queries). Currently, the single Article query example throws an error, but if you change the GraphQL query to what's in the PR, it returns the file URL in fieldImage.
Before:
After:

Modify Article query so image url resolves

---

gridsome/app/entry.client.js

My gridsome website is deployed on `example.org`. I have a link pointing to `//examples.org:8080/foobar`.
This global 'click' event should account for the port in its test, otherwise, it mistakenly thinks this is an internal link and overrides the domain.
N.B: honestly this whole event handler seems like a terrible idea... It's easy to circumvent by right clicking on an anchor and do "Open in a new..." (tab, window, whatever) and I can see a lot of edge cases arise. People should just use `g-link`. But that's just my two cents.

Global 'click' event listener should account for port

---

packages/source-datocms/index.js

In graphQL it'd be great to access the `api_key` prop that Dato's JS lib provides.
The original field can be found in the [documentation](https://www.datocms.com/docs/content-management-api/resources/field).
It's very useful when using Dato's [Modular Content Blocks](https://www.datocms.com/docs/content-modelling/modular-content) as it helps identify which block type to use on the frontend.
Thanks

Add apiKey to response fields in DatoCMS

---

gridsome/lib/app/queue/FileProcessQueue.js
gridsome/lib/app/queue/ImageProcessQueue.js
gridsome/lib/workers/html-writer.js

This `catch` in some files are duplicate because they just rethrow the same exception without any handling.

refactor: remove duplicate exception rethrow

---

gridsome/app/app.js

There are typos in [this file](https://github.com/gridsome/gridsome/blob/master/gridsome/app/app.js) in the spelling of "graphql". The typos do not currently cause any issues as they are utilizing default imports and the names match throughout the file. The fix passed test on my local machine.

fixed typo in file

---

packages/source-airtable/README.md
packages/source-airtable/index.js
packages/source-airtable/package.json
yarn.lock

Closes #29. Here is the first official draft of the @gridsome/source-airtable plugin. I had a version that worked, but started having issues with error relating to duplicate route names, so could not verify that this is 100% working before pushing:
`TypeName > Failed to add node: Duplicate key for property path: /<routepath>/slug`
Also had a version with class syntax, but with some issues. Decided to push simple object syntax version for now, instead of spending more time on potentially improved class syntax.
@hjvedvik please have a look and advice how to proceed in regards to "duplicate route names" issue, as well as the overall plugin.

feat(source-airtable): Add airtable source plugin

---

gridsome/app/directives/image.js

Fixed an issue where the g-image component was loading images twice.
Tested on latest browsers (edge, chrome, firefox) simulating HiDPI and iPhone 5 screens and it is working fine - a single image gets loaded on the correct width.
On IE11 the images won't load (only the pixelated SVG) but that also happens on the master branch of the base repo.

Fix issue #438

---

gridsome/lib/graphql/types/date.js

Fixes an issue where the value for a `date` field is `null or falsy`. When `falsy or null` it shouldn't try to format the date, but rather just return null

Return null if date value is null or falsy

---

gridsome/lib/app/loadConfig.js

bugs: when you add custom config icon below, icon still generate default
```
module.exports = {
icon: {
favicon: {
src: './src/my-favicon.png',
sizes: [16, 32, 96, 192]
},
touchicon: {
src: './src/my-touchicon.png',
sizes: [76, 152, 120, 167],
precomposed: true
}
}
}
```
then the pull request can solve it. please review it, thanks @tomtev

fix load config icon

---

gridsome/lib/graphql/__tests__/nodes.spec.js
gridsome/lib/graphql/types/image.js

This is just a small PR that adds support for the image background argument in GraphQL queries.

add background argument to GraphQLImage

---

packages/source-airtable/README.md

**Swap from <> to {} so that the url doesn't look like ` https://airtable.com//api/docs#curl/introduction`** 
It looks like the parser is converting `<YOUR_BASE_ID>/api/docs#curl/introduction` to `<your_base_id>/api/docs#curl/introduction</your_base_id>` on https://gridsome.org/plugins/@gridsome/source-airtable
I wasn't able to figure out how to run this locally to double check that this fixes the issue, but if someone could direct me on that, I can add it to the docs.

Update Base ID Url

---

gridsome/lib/graphql/__tests__/nodes.spec.js
gridsome/lib/graphql/createFieldTypes.js

This PR adds support for image arrays and arrays of other custom types in GraphQL.
E.g. you can now write 
```
title: Test
images:
- "./image1.jpg"
- "./image2.jpg"
- "./image3.jpg"
```
and the images will be resolved correctly, including support for arguments in GraphQL queries:
```
testPost (id: "1") {
title
images (width: 300, height: 300)      
}
```

Fix grapghql list resolve

---

packages/source-wordpress/index.js

Looks like some post types (custom post types?) have a "rest_base" starting with /. This makes the fetch request look something like <BASE_URL>/wp-json/wp/v2//api/winners which fails.
Adding trim start to `options.rest_base` should solve the double slash issue

Remove starting slash for some Post Types 'rest_base'

---

packages/source-wordpress/index.js

I suggest adding meta data to graphql for taxonomy terms. 
`add_term_meta`, `update_term_meta` and `get_term_meta` are core WordPress functions. The WP API adds a meta field by default on taxonomy terms.

WordPress Source: Enh(taxonomy): add meta support

---

.github/ISSUE_TEMPLATE/bug-report---.md

A dedicated `info` command was shipped with the recent release with which all the user has to do is just paste the information that shows up by firing in the respective command.

[Meta]: update bug report template

---

packages/source-drupal/README.md

For a taxonomy term page, instead of getting all the articles and filtering them down, you can use a `Fragment` (or `Inline Fragment`) to join data between two collections. The relationship already exists thanks to JSON API so we can take advantage of that.

Add join example between taxonomy term and article

---

packages/source-wordpress/index.js

Adding support for user-defined REST endpoints in WordPress.
gridsome.config.js:
```
plugins: [
{
use: '@gridsome/source-wordpress',
options: {
baseUrl: 'http://localhost:8000',
apiBase: 'wp-json',
typeName: 'WordPress',
perPage: 100,
concurrent: 10,
routes: {
post: '/:slug/',
product: '/product/:slug/'
},
customEndpoints: [
{
name: "WPMenu",
apiRoot: "my_api/v1",
apiBase: "menu"
}
]
}
}
],
```
NavigationComponent.vue
```
<template>
...
</template>
<static-query>
query Menu {
WPMenu(id: "header") {
menu {
menu_items {
title,
url,
menu_order
}
}
}
}
</static-query>
```
To pull from custom-defined REST routes you need to be able to change the standard `wp/v2` portion of the WordPress REST route to something specific to your plugin or theme.
[WordPress Reference]( …

feat(source-wordpress): custom REST route support for source WordPress

---

gridsome/lib/app/loadConfig.js
gridsome/lib/build.js
gridsome/lib/server/createRenderFn.js
gridsome/lib/workers/html-writer.js

Gridsome use vue-server-renderer for build static page. But without settings shouldPrefetch/shouldPreload.
Documentation https://ssr.vuejs.org/guide/build-config.html#client-config
Source https://github.com/vuejs/vue/blob/master/src/server/create-renderer.js#L51
**Problem**
Some sites maybe using many dynamic imports (webpack function). Default generate many-many the link of assets (for prefetch/preload). This is problem for large sites. 
```
computed: {
blocks() {
return this.blocksNames.map(name => {
const source = name
return  () => import( /* webpackChunkName: "[request]" */ `~/components/${name}.vue` )
})
},
```
Page in dist (before PR)
**Solution**
This PR adding the functionality to control prefetch/preload the links of assets.
Also requires the object 'prefetch' (and/or 'preload') …

Control prefetch/preload the links of assets

---

gridsome/lib/server/createHTMLRenderer.js
gridsome/lib/server/createRenderFn.js

Hi @hjvedvik,
We discussed via Discord a few weeks ago about further breaking out index.html template variables for use when overloading the original index.html. While I personally only needed the `gridsome:hash` broken out, I can see a need for break each out into their own template variable. 
This is my PR to do so.
We have used Gridsome to develop templates for Django (Django-templates) and breaking out these template properties will enable them to be wrapped in Django `{% block %}` statements when trying to integrate.
I look forward to your review and seeing what needs to change if any! Thanks!
---
When overloading (or replacing) the standard index.html file, a user may need to break out the various `${ head }` template variables for use in their chosen platform.
This sanely breaks …

Break out individual Vue-Meta items for use in static rendering

---

packages/source-datocms/index.js

Adding item.position will get the sort order from the CMS.
Thanks to @matjack1 from Dato for the hot tip!

Add item.position to collection node

---

packages/remark-prismjs/README.md
packages/remark-prismjs/index.js

This PR adds an option to disable highlighting of inline code blocks.
I've also updated the docs.
Closes #771

feat: option to skip inline blocks

---

packages/source-wordpress/README.md

Updating the docs for source-wordpress to reflect `customEndpoints` option.

Adding customEndpoints usage to docs for source-wordpress

---

gridsome/package.json
yarn.lock

Hey 👋 
We cannot install `Gridsome` with the latest version of Node.js since `sharp` doesn't compile.
Updating `sharp` to the latest version fix this issue.

Update sharp for supporting Node 13.x

---

gridsome/lib/app/queue/ImageProcessQueue.js

In ImageProcessQueue I get empty arrays sometime. This error blocks my building process.

Do not try to read sets array if empty in ImageProcessQueue

---

packages/source-airtable/package.json
yarn.lock

This updates `airtable` to the latest version, v0.7.2. [See the changelog][1] for more info on what changed, but I expect no breaking changes.
[1]: https://github.com/Airtable/airtable.js/blob/v0.7.2/CHANGELOG.md

chore(airtable): upgrade `airtable` to latest version, v0.7.2

---

gridsome/lib/app/build/executeQueries.js
gridsome/lib/pages/pages.js
gridsome/lib/server/Server.js

Just having this as a draft for the moment.
@hjvedvik  I've got reservations making the query source and document available to the prod build by default for performance. Wondering if this should be opt in via a config setting?
Also, thinking if it's available to the static version it should be the same in development.

feat(query): make query available to build

---

packages/source-airtable/README.md
packages/source-airtable/index.js

Airtable requires you to specify a `view` if you want to get your records in the order specified there. This PR adds support for passing this select option object and defaults to an empty one to make it work the same way it did before.

Allow users to pass select options object to Airtable's queries

---

packages/source-contentful/index.js

Iterate based on the fields on the schema, so we can catch the missing fields. Closes #864.

fix(source-contentful): properly handle empty asset fields

---

gridsome/lib/develop.js

Setting `configureWebpack.devServer.watchOptions` is currently passed to webpack, but actually needs to be set on the middleware to have effect. 
`watchOptions` is needed to enable polling, which is required when running gridsome in a Docker for Windows container.

Use webpack watchOptions config for webpack-dev-middleware

---

packages/source-ghost/package.json

Updated the `@tryghost/content-api` package. Closes #867.

feat(source-ghost) upgrade content-api to support Ghost v3

---

packages/source-ghost/ghost-schema.js
packages/source-ghost/index.js
yarn.lock

Adds explicit schemas so that ghost fields on posts, pages, authors and tags that are empty can still be queried. Relates to #871.

fix(source-ghost) add explicit schemas for ghost types

---

packages/source-wordpress/index.js

Update error formatting in fetch method.
Use `response.status`, instead of trying to destructure `status` from `response.data`, as if there is an error, then data will be null - therefore `status` cannot be destructured from it.

fix(source-wordpress) Update error formatting in fetch method

---

gridsome/lib/utils/sysinfo.js

We encountered an issue on circleci regarding the cpu count. They advertise more cpus than you are allowed to use, so we got some memory errors. We solved this by using an environment variable as proposed in this pull request.

use env variable for cpu count and removed unused model from cpus

---

gridsome/lib/pages/pages.js

Added a return if no page is found, otherwise an error is thrown `Cannot read property 'internal' of undefined`, and the build breaks.
I don't know whether it should just silently return, or perhaps log a message that the page wasn't found?

fix(pages API) Update removePage to return if no page found

---

packages/transformer-remark/README.md
packages/transformer-remark/index.js

Integrates a new `config` property for the remark transformer to change the default remark options.
Fixes #726 
If I have missed something, please let me know :)

feat(transformer-remark) Parser Options

---

gridsome/lib/webpack/compileAssets.js

When I added the following performance option:
```
configureWebpack: {
// merged with the internal config
performance: {
hints: "error",
maxEntrypointSize: 1
}
},
```
The build failed, but the error message was not helpful:
```
(node:12752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined
```
This is because the `stats.compilation.errors` does not contain an `.error` subkey in case of a performance issue (when some assets are to big for instance).
This PR fixes this (and uses `flatMap` which looks tidier)

fix(build): handle errors without an sub-error

---

gridsome/app/app.js
gridsome/lib/webpack/modules/assets.js

This will allow users to use `GLink` as well as `g-link` and `GImage` along with `g-image`.
Fixes #983.

Allow GLink and GImage to be used

---

gridsome/app/entry.client.js
gridsome/app/graphql/guard.js

Fixes #1043 
This prefixes the route with the configured `pathPrefix` when attempting to do a full route reload, as client side routes aren't prefixed, but the server will need them.
I'm not sure how to test locally so I'm not sure if the `guard.js` file changes are ok, I just included the config in the same way it was already included in the `entry.client.js` file.

Prefix route with pathPrefix when hard reloading view

---

gridsome/app/components/Image.js

This is to fix an issue where srcset is not generated by Gridsome but does exist on the object given to g-image.

Check that srcset is array before joining, else expect it to be string

---

gridsome/package.json

To prevent issues like https://github.com/oliverfindl/vue-svg-inline-loader/issues/39
According to https://github.com/gridsome/gridsome/pull/982, the `gridsome/app` is expected to somehow depend on `core-js`

Add core-js as an explicit dependency

---

packages/source-ghost/index.js

Added tags and author references to Ghost static pages. Previously they were only set for posts.

Add tags and author references to static pages for source-ghost plugin

---

packages/source-ghost/ghost-schema.js

Simple change, just adds the reading_time parameter ([see ghost api docs](https://ghost.org/docs/api/v3/content/#posts))

feat(ghost): Add reading_time for ghost posts

---

gridsome/app/utils/helpers.js

This allows for Pager links to have a trailing slash or not have trailing slash depending on vue route

Add suffix test to allow for trailing slash on Pager component

---

gridsome/lib/pages/__tests__/pages.spec.js

The unit test have started failing on CircleCI, but am having to fix it with a useless escape character? [^**\\**/]
```
Expected: /^\/page\/([^/]+?)(?:\/(\d+))?(?:\/)?$/i
Received: /^\/page\/([^\/]+?)(?:\/(\d+))?(?:\/)?$/i
```

fix: unit test breaking on escape character in regex

---

packages/vue-remark/lib/utils.js

remark-cli cannot be imported/required, so vue-remark should not try
to import it as though it is a plugin.

Do not count remark-cli as a plugin in vue-remark

---

packages/transformer-remark/index.js

As mentioned in #237, the `excerpt` field is empty by default. Configuration can be passed to `gray-matter` to populate this field (#284), however `gray-matter` excerpts are not parsed when extracted this way.
This PR addresses this as follows:
- If the user has already got a gray-matter config to populate `excerpt`, it does not overwrite this value.
- If `excerpt` is empty, it populates it with:
- Raw text, as taken from `sanitizeHTML()`.
- Newlines are removed and replaced with spaces.
- The text is limited to at most `length` characters, but will not snip mid-word.
- `excerpt` is added to the schema, including a `length` argument, with a default of 200 characters.

transformer-remark: Populate excerpt with text

---

README.md

Updating to new Jamstack brand naming (jamstack.org has updated)
We should also update the repo description to `Jamstack` as well

docs: update JAMstack -> Jamstack

---

gridsome/package.json
yarn.lock

When I tried building my gridsome project on a node:14-alpine docker container (a lightweight linux container with Node.js 14), it failed because of the dependency on sharp ^0.23.2. As per the response of the Sharp maintainer in https://github.com/lovell/sharp/issues/2190, this would be solved by upgrading to sharp ^0.25.2 because its prebuilt binaries are no longer geared towards a specific Node.js version.
My own project seemed to run fine on sharp 0.25.2, but I must mention that I did not do extensive testing. 
This is my first gridsome pull request so please let me know if I'm not following the correct procedure here.

Update sharp dependency to ^0.25.2

---

gridsome/app/fetch.js

Several clients are reporting non-deterministic app crashes caused by a mismatch in hashes (#1032). This adds additional context to the error to make it easier to diagnose the root cause.

fix(app): add extra debugging output on hash mismatch failure

---

packages/source-airtable/README.md
packages/source-airtable/index.js
packages/source-airtable/package.json

Updated configuration to accept multiple tables as a source. Introduced new syntax with "tables" array but tried not to introduce breaking changes. It would just show deprecation warning when the old syntax is used.
Added option for linking tables: In Airtable when you set a field to link to another table api just returns  array od ids. Now it maps the actual objects to the ids and returns as a nested resource.
Also added syntax when you link to only one record in the table to conveniently return a first result as an object and not as an array. Inspired by "one to one" convention from relational databases.
I'm already using this implementation on my gridsome project, but I would like to hear comments if I did something wrong or unconventional, and if there are maybe some performance …

feat(source-airtable): add option for linked tables

---

gridsome/lib/app/PluginAPI.js

Update to use tapPromise instead of tapAsync.
I could only get the `onBootstrap` hook to work when I made this change, and I found it more helpful to use the promise style hooks. However, I can change the hook code to properly pass the async callback function  if you think it should be kept as `tapAsync`.

fix (Plugin API Hooks) - Promises

---

packages/cli/__tests__/create.spec.js
packages/cli/__tests__/gridsome.spec.js
packages/cli/__tests__/utils/helpers.js

- Added new helper method to be consumed across the entire test suite.
- Test case to ensure `create` command shows up an appropriate warning if a directory with the same name (which isn't empty) already exists in path.

tests: add new helper and increase coverage

---

packages/transformer-remark/README.md

Changed repository in remark links towards the newly named _main_ repository

Fixed remark example links

---

packages/plugin-sitemap/README.md
packages/plugin-sitemap/index.js

Adds a `lastmod` option to the page config of `plugin-sitemap`, requested in https://github.com/gridsome/gridsome/issues/1147:
```javascript
config: {
'/articles/*': {
changefreq: 'weekly',
priority: 0.5,
lastmod: '2020-02-19'
},
}
```

Sitemap plugin lastmod option

---

gridsome/lib/server/middlewares/assets.js

When using `gridsome develop`, assets like audio and video files are sent without the `Accept-Ranges` header. In Chrome, this means you can't set `currentTime` of an `<audio>` element (it will reset to `0`, see this [StackOverflow thread](https://stackoverflow.com/questions/37044064/html-audio-cant-set-currenttime)).
The second paramter of `res.end` can be omitted, as it will only be used when the first parameter is a string (see [`response.write`](https://nodejs.org/api/http.html#http_response_write_chunk_encoding_callback)).

Audio/video playback issues in Chrome

---

.gitignore
gridsome/app/components/Pager.js

Add more properties to Pajer.js component to allow users to set customs classes in navigation elements (First, Prev, Next, Last)
New properties
* firstClass: Custom class to the link to first element 
* prevClass: Custom class to the link to prev element 
* nextClass: Custom class to the link to first element 
* lastClass: Custom class to the link to last element 
* navClass: Custom class to all navigation elements (this class doesn't replace other custom classes
Add .idea/ to .gitignore

Pager.js: allow to set more classes

---

gridsome/lib/graphql/filters/__tests__/query.spec.js
gridsome/lib/graphql/filters/query.js
gridsome/lib/store/__tests__/lokiOps.spec.js
gridsome/lib/store/lokiOps.js

Hello,
This add missing loki operator `$refExists` and `$refListExists`.
That fix `Error: fun is not function` when we have an request like :
```gql
query {
allProductCategory(filter: { parent: { id: { exists: false } } }) {
totalCount
edges {
node {
name
parent {
id
}
}
}
}
}
```
Thanks

Add missing ref exists functions

---

packages/vue-remark/lib/codegen.js

Hello,
When create component with vue-class-component or Vue.extend
import return an VueComponent function not an Object.
So, i have added an branch in if to support this case
I test and don't change original behavior and work fine with the two form.
Also work fine with components in typescript (with vue-class-component in my case)

fix(vue-remark): add support VueComponent function

---

packages/remark-prismjs/README.md
packages/remark-prismjs/index.js
packages/remark-prismjs/parse-options.js

I add option `showLineNumbers: true` to display line numbers for `@gridsome/remark-prismjs`, and also tried to update the doc
this feature be mentioned at #1035  and #1048 
set in `gridsome.config.js` 
```js
{
remark: {
plugins: [
[
require('./script/remark-prismjs'),
{
// display line numbers alongside code
showLineNumbers: true
}
]
]
}
}
```
or if wish to only show line numbers on certain code blocks, leave false and use the `{ numberLines: true | number }` syntax below
````markdown
```js { numberLines: 21 }
interface IntersectionObserver {
readonly root: Element | null;
readonly rootMargin: string;
readonly thresholds: ReadonlyArray<number>;
disconnect(): void;
observe(target: Element): void;
takeRecords(): IntersectionObserverEntry[];
unobserve(target: Element): void;
}
```
````
that …

feature: add option to toggle line numbers alongside code

---

packages/source-strapi/README.md
packages/source-strapi/helpers/query.js
packages/source-strapi/index.js

The Strapi CMS features Collection Types as well as single Types.
Those Commits enable the plugin to fetch the Single Types as well.

Add Support for Strapi Source to fetch Single Types

---

packages/source-contentful/index.js
packages/source-contentful/package.json

This will solve #748 
Previously the Contentful source only returned the default locale of a field. As [mentioned in the Contentful docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/localization), the search parameter `locale=*` has to be provided to return all locales of a field. 
With the changes in this pull request, you can now define search parameters in the plugin configuration. 
```
{
use: '@gridsome/source-contentful',
options: {
space: process.env.CTF_SPACE_ID,
accessToken: process.env.CTF_ACCESS_TOKEN,
host: 'cdn.contentful.com',
environment: 'master',
typeName: 'Contentful',
parameters: {
locale: '*'
}
}
}
```

fix(source-contentful) add possibility to define search parameters in config

---

packages/remark-prismjs/README.md
packages/remark-prismjs/index.js

Prismjs's default classes for syntax highlighting can come into conflict with your own classes. Adding this plugin from prismjs lets us prefix its classnames so that we can avoid this. 
Before:
After:
I've ran into this issue myself and you can see examples of this causing issues even in Gridsome starters like [this one](https://calebanthony.github.io/gridsome-bulma/say-hello-to-gridsome). Notice how the code block looks weird, with anomalies like the giant number 5? That's from the conflicting number class from Bulma and number in Prismjs. I wonder if there should even be a prefix by default, if this really is so common, but I have implemented this as an option.

Add custom class prefix to remark-prismjs

---

gridsome/lib/server/Server.js

- This appears to fix a hard to figure out bug.
- Sometimes the `sockjs` 'connection' event would be called with `null` argument,
which would crash `gridsome develop`.
- I have not been able to debug it any further, or come up with a test which proves that
the issue is now fixed.
- There is a related bug from Sockjs-node: https://github.com/sockjs/sockjs-node/issues/121
- The error that used to appear always appeared like the following:
```
Site running at:
- Local:                 http://localhost:8080/
- Network:               http://192.168.1.134:8080/
Explore GraphQL data at: http://localhost:8080/___explore
/Users/myuser/work/playground/mysite/gridsome-site/node_modules/gridsome/lib/server/Server.js:110
this._app.clients[connection.id] = connection
^
TypeError: Cannot read property …
```

fix: sockjs when no connection `null` argument

---

packages/transformer-remark/README.md

There is a small typo in packages/transformer-remark/README.md.
Should read `guillemets` rather than `guillements`.

docs: Fix simple typo, guillements -> guillemets

---

gridsome/lib/app/loadConfig.js

Change to be compatible with sass-loader@8 as reported in #750.
The option `indentedSyntax` of the sass-loader is now defined under `sassOptions`.
This pull request modifies the default definition of gridsome to be compatible with the sass-loader configuration.
A description of the sassOptions of the sass-loader is given below:
webpack-contrib/sass-loader: Compiles Sass to CSS
https://github.com/webpack-contrib/sass-loader#sassoptions.

fix(sass-loader): improve default options (#750)

---

.circleci/config.yml
.gitignore
gridsome/lib/app/loadConfig.js
gridsome/lib/develop.js
gridsome/lib/plugins/vue-components/index.js
gridsome/lib/server/createRenderFn.js
gridsome/lib/webpack/createBaseConfig.js
gridsome/lib/webpack/modules/assets.js
gridsome/lib/webpack/plugins/corejsBabelPlugin.js
gridsome/package.json
packages/cli/lib/utils/index.js
packages/source-graphql/package.json
packages/vue-remark/index.js
packages/vue-remark/package.json
yarn.lock

**What's the problem this PR addresses?**
- Gridsome doesn't work with [Yarn PnP](https://yarnpkg.com/features/pnp).
- Gridsome is passing loaders to webpack using their name instead of absolute path
- Gridsome has some undeclared dependencies
Fixes https://github.com/gridsome/gridsome/issues/551 (cc @Js-Brecht)
Closes https://github.com/yarnpkg/berry/issues/1266 (cc @borisdiakur)
**How did you fix it?**
- Use `require.resolve` for webpack loaders (https://github.com/yarnpkg/berry/tree/eff8ffd607242d80adbeaa05ebf5453a68dd299b/packages/yarnpkg-doctor#no-unqualified-webpack-config)
- Add undeclared dependencies (https://github.com/yarnpkg/berry/tree/eff8ffd607242d80adbeaa05ebf5453a68dd299b/packages/yarnpkg-doctor#no-unlisted-dependencies)
- Resolve user defined plugins relative to the …

feat: support Yarn PnP

---

gridsome/app/components/Image.js

This PR fixes an issue where the browser wouldn't be able to save space for images even when this info was available 😢 
> Use both width and height to set the intrinsic size of the image, allowing it to take up space before it loads, to mitigate content layout shifts. 
> [`<img>`: The Image Embed element - HTML: Hypertext Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)

Fix `g-image` not adding `height` attribute

---

gridsome/app/directives/image.js

Keep displaying dataUri (placeholder) if loading the src results in error either due to file not found or being offline.

Add g-image fallback support

---

gridsome/app/components/Pager.js

Close #215
I wanted to use this option(#215), so I fixed it.
Pager component like this.
Option → `:showLinks="false"`
```vue
<Pager :info="$page.myobject.pageInfo" :showLinks="false"/>
```
See only next/prev links in pagination (numeric page links removed).

feat(pager): showLinks option show only prev/next links(#215)

---

gridsome/lib/plugins/TemplatesPlugin.js

Closes #1424 
```
Error: 'Page' is a reserved type name.
at exports.validateTypeName (/home/manu/stuff/gridsome/gridsome/lib/graphql/utils.js:30:11)
at setupTemplates (/home/manu/stuff/gridsome/gridsome/lib/plugins/TemplatesPlugin.js:136:5)
at new TemplatesPlugin (/home/manu/stuff/gridsome/gridsome/lib/plugins/TemplatesPlugin.js:161:23)
at Plugins.initialize (/home/manu/stuff/gridsome/gridsome/lib/app/Plugins.js:61:11)
at App.init (/home/manu/stuff/gridsome/gridsome/lib/app/App.js:128:18)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async App.bootstrap (/home/manu/stuff/gridsome/gridsome/lib/app/App.js:49:5)
at async module.exports (/home/manu/stuff/gridsome/gridsome/lib/app/index.js:12:3)
at async module.exports …
```

#1424 Validate template name - don't allow reserved names

---

packages/source-wordpress/index.js

The users endpoint of wp-json api by default provides 10 users (or authors).
Since the previous version was using a request without pagination some posts
could get null author fields causing problems in template building.
This small change turns them into paged requests like some other types are already
doing.

fix(source-wordpress): non-paginated request on users endpoint causing truncated data

---

gridsome/lib/app/loadConfig.js

favicon sizes must contain 192 and 196 as `192x192` is Google Developer Web App Manifest Recommendation and `196x196` is Android home screen icon

Update favicon sizes as per Google Developer Recommendation

---

packages/source-contentful/index.js

This is a really simple one-line change to the source contentful plugin that will pull the in the `metadata` field which contains tags as part of Contentful's new [tagging feature](https://www.contentful.com/help/tags/). This allows you to tag assets to organise content, and we're using it to help determine what content should get built or ignored in staging/prod versus development.
Here's a sample of what this looks like in GraphQL.

feat(source-contentful): added entry metadata

---

gridsome/lib/graphql/types/date.js
gridsome/lib/plugins/TemplatesPlugin.js
gridsome/lib/utils/constants.js
packages/vue-remark/lib/utils.js

Here I am adding support for Database formatted DateTime. 
Some of my imported data appear to be in this format and querying it via GraphQL yields an error, but `moment.js` can successfully parse the format. 
I hope this subtle change helps other projects facing the same Date type issue. 
example:
```
2011-02-25 23:59:59.999 +0530
```

Add database formatted DateTime to GraphQL

---

packages/cli/lib/commands/create.js

Currently, an attempt to create a new project with the official [starter-kit-name](https://github.com/gridsome/gridsome/tree/master/packages/cli#creating-new-projects) syntax fails.
```sh
$ gridsome create my-app wordpress
Pick a package manager that will install dependencies npm
Do you want to use npm for all future Gridsome projects? No
❯ Clone wordpress
❯ Install dependencies with npm
Error: Command failed: git clone wordpress  --single-branch
```
It seems to have changed in 549d487704e1811582d45e435010cb86a2530c75
This PR aims at restoring this behavior.

fix(cli): support gridsome-starter-name syntax

---

packages/source-drupal/README.md
packages/source-drupal/lib/Entity.js

In Drupal's jsonapi response there is a `path` attribute, the value is an object with some attributes like `alias` see here: https://dev-campus-drupal-9.pantheonsite.io/jsonapi/node/article
When there are more then one article you see this when running `gridsome develop`:
```
DrupalNodePage > Failed to add node: Duplicate key for property path: [object Object]
DrupalNodePage > Failed to add node: Duplicate key for property path: [object Object]
DrupalNodeArticle > Failed to add node: Duplicate key for property path: [object Object]
```
Only one node for that type will ever get loaded into GraphQL. In the output above I should have 3 DrupalNodePages and 2 DrupalNodeArticle. But when I go into the GraphQL explorer I only have 1 of each type.
Evidence of error is apparent in #869 
They had a …

feat(drupal): handle path attribute in drupal's jsonapi response

---

gridsome/lib/plugins/TemplatesPlugin.js

When we use CJK characters as the routing path, gridsome returns an error because slugify result is an empty string that cannot be used as the routing path.
Although the URL without slugify may not be beautiful, users generally prefer to build successfully first and then look for a solution likes to add `slug` in the markdown file or use `:fileInfo__name` as route path if they are not satisfied with the encoded URL. (Relate issues #918, #956)
```
// case 1 (raw title fallback)
title: '테스트'
result: http://example.com/%ED%85%8C%EC%8A%A4%ED%8A%B8/
// case 2 (raw title fallback)
title: '中文测试'
result: http://example.com/%E4%B8%AD%E6%96%87%E6%B5%8B%E8%AF%95/
// case 3 (affected by slugify)
title: 'test 中文测试'
result: http://example.com/test/
// case 4
title: 'slugify() test'
result: …
```

feat(makePath): use raw string as a fallback when the slugify result is empty

---

gridsome/app/components/Image.js
gridsome/app/directives/image.js

See issue https://github.com/gridsome/gridsome/issues/1295#issuecomment-753877204
& the need for a lazy-loaded image where one might not have different sizes available:
```vue
<g-image :src="{
src: 'https://picsum.photos/200/300',
size: {width: 200, height: 300},
dataUri: 'data:image/gif;base64,R0lGODlhAQABAIABAP///wAAACwAAAAAAQABAAACAkQBADs=', // http://probablyprogramming.com/2009/03/15/the-tiniest-gif-ever
}" />
```

Optional srcset&sizes for custom g-image

---

gridsome/lib/app/loadConfig.js

Loads `.env.local` and environment-specific `.env.${NODE_ENV}.local`.
Also merges variables from multiple `.env.*` files with the base `.env`, similar to other tools like Vite and Vue CLI. (See  #1332)
Follows this order of precedence:
1. Existing env vars (since they're likely deployment-specific)
2. `.env.${NODE_ENV}.local`
3. `.env.${NODE_ENV}`
4. `.env.local`
5. `.env`
Implementation was based on [Vite's config](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/config.ts#L974-L1034)

Enable loading `.env.local` and `.env.*.local`

---

packages/transformer-remark/lib/plugins/file.js
packages/transformer-remark/lib/plugins/image.js

The return value matters for the visitor function. This bug was causing some images and links to be skipped when parsing the remark AST. The result was that images would show up as `img` with a invalid src value instead of `g-image`.
https://github.com/syntax-tree/unist-util-visit-parents#returns

Fix transformer-remark visit
